Update db.json
opensumi/website-data pull request #1
Opened 2022-11-24 08:28 UTC by winjo

add qcon

2022-11-24 08:30 UTC, erha19 commented on db.json
> +    {
这里还需要有一个 `"lang": "en"` 的信息用于英文页面

2022-11-24 08:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/opensumi/website-data?pullRequest=1) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/opensumi/website-data?pullRequest=1) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/opensumi/website-data?pullRequest=1) it.</sub>

2022-11-24 08:32 UTC, erha19 requested changes
CLA 签署一下 @winjo

2022-11-24 09:57 UTC, erha19 commented on db.json
> +    {
@winjo 看下这个

2023-05-22 03:50 UTC, Ricbet approved these changes

2023-06-28 02:26 UTC, erha19 approved these changes

2023-06-28 02:26 UTC, merged